### PR TITLE
Respond with newline-separated queue on @LIST

### LINKED ISSUE #3: QOL: Add the ability to list queued messages
This would be a command (i.e. `@LIST`) and send a list of both the sender's queued words and all queued words.

### PR DESCRIPTION
**Pull request by cgccuser**
Closes #3

### CODE REVIEW

**Comment by GingerIndustries** [comment]
A few suggestions:

1. Reply to the user sending the command (like the other messages do)
2. Indicate which ones belong to the sending user

**Comment by cgccuser** [comment]
@GingerIndustries It already replies to the user sending the command

**Comment by cgccuser** [comment]
@GingerIndustries It now puts a `* ` before word requests made by you, but it looks at usernames instead of user ids because the word cache uses `user_name` instead of `user_id`.

**Comment by GingerIndustries** [comment]
@cgccuser It should use the ID. You can fix that if you want.

**Review by GingerIndustries — CHANGES_REQUESTED** [review]
Change this to use IDs

**Pull request merged**
